language: python
python:
  - '3.9'
install:
  - pip install pipenv
  - pipenv install --system --dev
  - pip install .
script:
  - flake8 hass_deps
  - black --check hass_deps
  - mypy --strict hass_deps
before_deploy:
  - git describe --tags > VERSION
deploy:
  provider: pypi
  skip_cleanup: true
  user: nickw444-deploy
  password: "$PYPI_PASSWORD"
  on:
    tags: true
    python: 3.9
env:
  global:
    secure: dlCqScbSkzJFeCZJ2tgMhv+Y27InBfdfYnKu5Ky4gJH1IAxxa3Gk/S6GF4gcURH0miqMsx7sD87f+T9CHFWw5Q8yfGrUtcdQuQVXll0kChHvPb4i39TzaMRALW1GaTT05Z2S3Wwq+SutQoUgYu/gg6kBeHycnxyHHjDhUSTvB1XN8jDJdgxG9Ja2oPwsuQ9nPxTxLeRUfugLVKxl4UPq8v4m54GF/mXoXFo6NB8rqm2LytJn9hnQZpmPGthAsb7mBD7sqFErUxzsOc0tDoqsoyQMy7Wq2ymnRLoy1c8Txwkw9Q205Qh2Cff6+YMtsCUKiKHgHZow5KMQm/hB+2sM4Pbz6sxtSDrA1boUtuXNieCuAhR1YmJsCFgqFfCRZgVXfuqfnCqBXOjtfKEidBfZ4i5VdF4YRq1XZgKyHiVeaUcQcqbR1wehKVExkTHMy7AkhxXI71p+di03I+AiZcGGApo83ELRo2h8Sl3m7kY9l22h7BxpqBLo6p+RR+GQz+goLqb0ET8Pv12XnG4TvJ1x8JpHO8sFZav0WdaU6SsftJQ0dP+U0hRtn5+2592B9gWZnaeS+whztwceFysHRwxCbvNqLQiw8TAMw1x2anKiIUHSzpu2Edj7uP1aFgH9ZPuV2CNG+dDwj+8iW8mdKQ+1qYibTl1QifFLVpFTNPKf2jI=
