language: python
python:
  - '3.9'

install:
  - pip install pipenv
  - pipenv install --system --dev
  - pip install .

script:
  - flake8 hass_deps
  - black --check hass_deps
  - mypy --strict hass_deps

before_deploy:
  - git describe --tags > VERSION

deploy:
  provider: pypi
  skip_cleanup: true
  user: nickw444-deploy
  password: "$PYPI_PASSWORD"
  on:
    tags: true
    python: 3.9
